// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMtelQ_TLi-MIPTqLnPhGuZw8R9cNl0Wg',
    appId: '1:972154503554:web:5490fa71e941b2dc48cf9b',
    messagingSenderId: '972154503554',
    projectId: 'thuth-511c5',
    authDomain: 'thuth-511c5.firebaseapp.com',
    storageBucket: 'thuth-511c5.firebasestorage.app',
    measurementId: 'G-WB9J56CHMD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_FdE242DotoRnikIVxtCT3XJ9lJusPlM',
    appId: '1:972154503554:android:cdc8df95e8fbba3c48cf9b',
    messagingSenderId: '972154503554',
    projectId: 'thuth-511c5',
    storageBucket: 'thuth-511c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn2RenNKtR-pVOP1Z9g9vhIvkLWts-CZs',
    appId: '1:972154503554:ios:868b4dee70fbae7848cf9b',
    messagingSenderId: '972154503554',
    projectId: 'thuth-511c5',
    storageBucket: 'thuth-511c5.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn2RenNKtR-pVOP1Z9g9vhIvkLWts-CZs',
    appId: '1:972154503554:ios:868b4dee70fbae7848cf9b',
    messagingSenderId: '972154503554',
    projectId: 'thuth-511c5',
    storageBucket: 'thuth-511c5.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMtelQ_TLi-MIPTqLnPhGuZw8R9cNl0Wg',
    appId: '1:972154503554:web:f4ddd8309ddb78b848cf9b',
    messagingSenderId: '972154503554',
    projectId: 'thuth-511c5',
    authDomain: 'thuth-511c5.firebaseapp.com',
    storageBucket: 'thuth-511c5.firebasestorage.app',
    measurementId: 'G-VRY062DF11',
  );
}
